// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantBasedPizza.OrderManager.Infrastructure;

#nullable disable

namespace PlantBasedPizza.OrderManager.Infrastructure.Migrations
{
    [DbContext(typeof(OrderManagerDbContext))]
    [Migration("20250821080215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantBasedPizza.OrderManager.Core.DeliveryDetails", b =>
                {
                    b.Property<int>("DeliveryDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryDetailsId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "addressLine1");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "addressLine2");

                    b.Property<string>("AddressLine3")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "addressLine3");

                    b.Property<string>("AddressLine4")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "addressLine4");

                    b.Property<string>("AddressLine5")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "addressLine5");

                    b.Property<string>("OrderIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "postcode");

                    b.HasKey("DeliveryDetailsId");

                    b.HasIndex("OrderIdentifier")
                        .IsUnique();

                    b.ToTable("DeliveryDetails");

                    b.HasAnnotation("Relational:JsonPropertyName", "deliveryDetails");
                });

            modelBuilder.Entity("PlantBasedPizza.OrderManager.Core.Order", b =>
                {
                    b.Property<string>("OrderIdentifier")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "orderIdentifier");

                    b.Property<bool>("AwaitingCollection")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "awaitingCollection");

                    b.Property<string>("CustomerIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "customerIdentifier");

                    b.Property<DateTime?>("OrderCompletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "orderCompletedOn");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "orderDate");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "orderNumber");

                    b.Property<DateTime?>("OrderSubmittedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "orderSubmittedOn");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "orderType");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "totalPrice");

                    b.HasKey("OrderIdentifier");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("PlantBasedPizza.OrderManager.Core.OrderHistory", b =>
                {
                    b.Property<int>("OrderHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "orderHistoryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderHistoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<DateTime>("HistoryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "historyDate");

                    b.Property<string>("OrderIdentifier")
                        .HasColumnType("text");

                    b.HasKey("OrderHistoryId");

                    b.HasIndex("OrderIdentifier");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("PlantBasedPizza.OrderManager.Core.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "orderItemId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "itemName");

                    b.Property<string>("OrderIdentifier")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "quantity");

                    b.Property<string>("RecipeIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "recipeIdentifier");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderIdentifier");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("PlantBasedPizza.OrderManager.Infrastructure.OutboxItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.ToTable("orders_outboxitems", (string)null);
                });

            modelBuilder.Entity("PlantBasedPizza.OrderManager.Core.DeliveryDetails", b =>
                {
                    b.HasOne("PlantBasedPizza.OrderManager.Core.Order", null)
                        .WithOne("DeliveryDetails")
                        .HasForeignKey("PlantBasedPizza.OrderManager.Core.DeliveryDetails", "OrderIdentifier");
                });

            modelBuilder.Entity("PlantBasedPizza.OrderManager.Core.OrderHistory", b =>
                {
                    b.HasOne("PlantBasedPizza.OrderManager.Core.Order", null)
                        .WithMany("History")
                        .HasForeignKey("OrderIdentifier")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlantBasedPizza.OrderManager.Core.OrderItem", b =>
                {
                    b.HasOne("PlantBasedPizza.OrderManager.Core.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderIdentifier")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlantBasedPizza.OrderManager.Core.Order", b =>
                {
                    b.Navigation("DeliveryDetails");

                    b.Navigation("History");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
